### ISSUE TITLE
[1.14.4] Unable to connect to dedicated server--rejected their client side version number

### ISSUE THREAD

**Issue by ProsperCraft** [eideehi/ExpBottling#1]
exp_bottling-1.14.4-1 same mod uploaded from the client.
--------------------------------------------------------------------------------------------
[13:03:02.941] [Netty Epoll Server IO #2/ERROR] [ne.mi.fm.ne.NetworkRegistry/NETREGISTRY]: Channels [exp_bottling:exp_bottling] rejected their client side version number
----------------------------------------------------------------------------------------------------

[ne.mi.fm.ne.FMLHandshakeHandler/FMLHANDSHAKE]: Terminating connection with client, mismatched mod list

Logs-

Client-
[latest.log](https://github.com/eideehi/ExpBottling/files/3503162/latest.log)
[debug.log](https://github.com/eideehi/ExpBottling/files/3503164/debug.log)

Server-
[latest.log](https://github.com/eideehi/ExpBottling/files/3503166/latest.log)
[debug.log](https://github.com/eideehi/ExpBottling/files/3503167/debug.log)

**Comment by eideehi** [comment]
As for this matter, I tried to confirm by setting up a server, but I couldn't reproduce it.
Does the problem occur even if Mod is only 'EXP Bottling'?

**Comment by eideehi** [comment]
As for this matter, I tried to confirm by setting up a server, but I couldn't reproduce it.
Does the problem occur even if Mod is only 'EXP Bottling'?

**Comment by eideehi** [comment]
Closed due to no response for a long time.
